config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  filter :locale

  root 'main#index'

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login' => 'user_sessions#new', :as => :login

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  end

  namespace 'admin' do
    devise_for :users, ActiveAdmin::Devise.config
  end

  ActiveAdmin.routes(self)

  resources :flickr

  mount ApiFlashcards::Engine, at: '/api'
  mount Sidekiq::Web, at: '/sidekiq'

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout' => 'user_sessions#destroy', :as => :logout

    resources :cards do
      collection do
        get :parse_form
        post :parse_words
      end
    end

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'

    get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
    put 'profile/:id' => 'profile#update', as: :profile
  end
end

app/models/card.rb
# coding: utf-8
require 'super_memo'

class Card < ActiveRecord::Base

  attr_accessor :flickr_search_query, :remote_image_url

  belongs_to :user
  belongs_to :block

  before_validation :set_review_date_as_now, on: :create
  validate :texts_are_not_equal
  validates :original_text, :translated_text, :review_date, presence: { message: 'Необходимо заполнить поле.' }
  validates :user_id, presence: { message: 'Ошибка ассоциации.' }
  validates :block_id, presence: { message: 'Выберите колоду из выпадающего списка.' }
  validates :interval, :repeat, :efactor, presence: true

  mount_uploader :image, CardImageUploader

  scope :pending, -> { where('review_date <= ?', Time.now).order('RANDOM()') }

  def self.pending_cards_notification
    users = User.where.not(email: nil)
    users.each do |user|
      if user.cards.pending.any?
        CardsMailer.pending_cards_notification(user.email).deliver
      end
    end
  end

  protected

  def set_review_date_as_now
    self.review_date = Time.now
  end

  def texts_are_not_equal
    if full_downcase(original_text) == full_downcase(translated_text)
      errors.add(:original_text, 'Вводимые значения должны отличаться.')
    end
  end

  def full_downcase(str)
    str.mb_chars.downcase.to_s.squeeze(' ').lstrip
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = 'Вы обратились к несуществующей записи.'
    redirect_to root_path
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:destroy, :edit, :update, :set_as_current,
                                   :reset_as_current]

  def index
    @blocks = current_user.blocks.all.order('title')
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def destroy
    @block.destroy
    respond_with @block
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def parse_form
  end

  def parse_words
    AddingWordsFromUrlJob.perform_later(current_user.id, current_user.blocks.first, parse_words_params.to_h)
    redirect_to cards_path, notice: t(:words_parsing)
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      track_user_created_card
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    respond_with @card
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def parse_words_params
    params.require(:parse_form).permit(:original_text_element, :translated_text_element, :url, :row_element)
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id, :user_id, :remote_image_url)
  end
end

app/controllers/dashboard/profile_controller.rb
# coding: utf-8
class Dashboard::ProfileController < Dashboard::BaseController

  respond_to :html

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path,
                  notice: 'Профиль пользователя успешно обновлен.'
    else
      respond_with current_user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :locale)
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController

  respond_to :html, :js

  def index
    if params[:id]
      @card = current_user.cards.find(params[:id])
    else
      if current_user.current_block
        @card = current_user.current_block.cards.pending.first
      else
        @card = current_user.cards.pending.first
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def review_card
    @card = current_user.cards.find(params[:card_id])
    @oncheck = SuperMemo.new(@card, trainer_params[:user_translation])
    if upd = @oncheck.card_update
      flash[:notice] = t(:correct_translation_notice)
    elsif upd.nil?
      flash[:alert] = t(:incorrect_translation_alert)
    else
      flash[:alert] = t 'translation_from_misprint_alert',
                        user_translation: trainer_params[:user_translation],
                        original_text: @card.original_text,
                        translated_text: @card.translated_text
    end
    track_user_reviewed_card
    redirect_to trainer_path
  end

  private

  def trainer_params
    params.permit(:user_translation)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: 'Пользователь успешно удален.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for card do |f| %>
  <div class="form-group">
    <%= f.input :original_text,  as: :text, label: 'Оригинал',
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <div class="form-group">
    <%= f.input :translated_text,  as: :text, label: 'Перевод',
                input_html: { class: 'form-control', required: true } %>
  </div>

  <div class="form-group">
    <%= f.input :image, as: :file, label: 'Изображение' %>
    <%= f.input :image_cache, as: :hidden %>
  </div>

  <div class="form-group">
      <%= link_to t(:load_from_flickr), '#', id: 'load-from-link', class: 'btn btn-primary' %>
      <div class="row" id="flickr-search-block">
          <div class="col-xs-3">
              <%= f.input :flickr_search_query, as: :string, label: false, required: false,
              input_html: { class: 'form-control' } %>
              <%= f.input :remote_image_url, as: :hidden %>
          </div>
          <div class="col-xs-3">
              <%= link_to t(:search_in_flickr), '#', class: 'btn btn-default', id: 'flickr-search-button' %>
          </div>
          <div id="flickr-images-block"></div>
      </div>
  </div>
  <div class="form-group">
      <div class="well" id="flickr-selected-image-block">
          <%= image_tag '', id: 'flickr-selected-image' %>
      </div>
  </div>
  <div class="form-group">
    <%= f.input :block_id, collection: current_user.blocks.all.order('title'),
                      prompt: 'Выберите колоду', label: 'Колоды',
                      input_html: { class: 'form-control', required: true } %>
  </div>

  <% if card.image? %>
    <div class="form-group">
      <%= f.input :remove_image, as: :boolean, label: 'Удалить изображение' %>
      <div class="row">
        <div class="col-xs-6 col-md-4 card_image">
          <p class="thumbnail">
            <%= image_tag card.image_url %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <%= f.button :submit, 'Сохранить', class: 'btn btn-default' %>
<% end %>

app/views/dashboard/cards/edit.html.erb
<h2>Редактировать карточку</h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/index.html.erb
<div class="btn btn-default pull-right">
    <%= link_to t(:parse_link), parse_form_cards_path %>
</div>
<br />
<hr>
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Оригинал</th>
    <th>Перевод</th>
    <th>Пересмотр</th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @cards.each do |card| %>
    <tr class="table table-hover table-condensed">
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
      <td><%= link_to 'Редактировать', edit_card_path(card) %></td>
      <td><%= link_to 'Удалить', card, method: :delete,
                      data: { confirm: 'Удалить запись?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/dashboard/cards/new.html.erb
<h2>Добавить карточку</h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/parse_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading" id="phead">Parse words from external URL</div>
    <div class="panel_body">
        <%= simple_form_for :parse_form, url: parse_words_cards_path do |f| %>
        <div class="form-group">
            <%= f.input :url, label: t(:parse_url), input_html: {class: 'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.input :row_element, label: t(:parse_row), input_html: {class: 'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.input :original_text_element, label: t(:parse_original), input_html: {class: 'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.input :translated_text_element, label: t(:parse_translated), input_html: {class: 'form-control'} %>
        </div>
        <div class="form-group">
            <%= f.button :submit, t(:parse_submit), class: 'btn btn-primary' %>
        </div>
        <% end %>
    </div>
</div>